"""Add vision column to research_teams

Revision ID: 437f8240b431
Revises: 1134e32cfeeb
Create Date: 2026-07-15 16:40:55.921275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437f8240b431'
down_revision = '1134e32cfeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vision', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_teams', schema=None) as batch_op:
        batch_op.drop_column('vision')

    # ### end Alembic commands ###
