"""remplace email par whatsapp dans team_member_drafts

Revision ID: 7e7d69a6b10c
Revises: 437f8240b431
Create Date: 2026-07-16 00:08:28.411996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7d69a6b10c'
down_revision = '437f8240b431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=30), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('whatsapp')

    # ### end Alembic commands ###
